name: Selenium Test CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # ✅ Correct step syntax (hyphen + space)

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Chrome & ChromeDriver
        uses: browser-actions/setup-chrome@v1  # ✅ Correct action name

      - name: Run tests
        run: mvn clean test
